#!/usr/bin/env python3
# testing webhook

from init.make_folder import make_folder
from fetch.parse import parse_manager
from create.create_file import create_file

import os
import argparse

app_name = "cppt"

def create(args):
    file_name = args.filename
    file_name_without_ext = file_name[:file_name.rfind(".")]
    create_file(args.path, {"name": file_name_without_ext})


def init(args):
    print("Initialise")
    base_path = args.path
    print("base_path: " + base_path)
    make_folder(base_path)


def fetch(args):
    print("Fetch")
    base_path = args.path
    app_folder_path = base_path + "/.{}".format(app_name)
    if not os.path.exists(app_folder_path):
        make_folder(base_path)
    parse_manager(base_path)


parser = argparse.ArgumentParser(prog='{}'.format(app_name),
                                 usage='{} subcommand'.format(app_name),
                                 description='Download and run testcases from different online judges.',
                                 add_help=True)

subparsers = parser.add_subparsers(title='subcommands',
                                   description='valid subcommands',
                                   help='additional help')

init_parser = subparsers.add_parser('init',
                                    help="Create base folder",
                                    usage="{} init [-p path]".format(app_name))

init_parser.add_argument("-p", '--path',
                         metavar='path',
                         type=str,
                         default=".",
                         help='the path to folder')

init_parser.set_defaults(func=init)

fetch_parser = subparsers.add_parser('fetch',
                                     help="Fetch a problem",
                                     usage="{} fetch [-p path]".format(app_name))

fetch_parser.add_argument("-p", '--path',
                          metavar='path',
                          type=str,
                          default=".",
                          help='the path to folder')

fetch_parser.set_defaults(func=fetch)

create_parser = subparsers.add_parser('create',
                                      help="Create a task file",
                                      usage="{} create [-p path] filename".format(app_name))

create_parser.add_argument("-p", '--path',
                           metavar='path',
                           type=str,
                           default=".",
                           help='the path to folder')

create_parser.add_argument('filename',
                           type=str,
                           help='name of the file (with file extension) to be created')

create_parser.set_defaults(func=create)

args = parser.parse_args()
print(args)
if (hasattr(args, "func")):
    args.func(args)
else:
    parser.print_help()
